const { Telegraf } = require('telegraf')
require('dotenv').config()
/*подключаю команды */
const airkiss = require('./commands/airkiss')
const bite = require('./commands/bite')
const blush = require('./commands/blush')
const cry = require('./commands/cry')
const cuddle = require('./commands/cuddle')
const dance = require('./commands/dance')
const drool = require('./commands/drool')
const happy = require('./commands/happy')
const help = require('./commands/HelpCommand')
const hit = require('./commands/hit')
const hug = require('./commands/hug')
const kill = require('./commands/kill')
const kiss = require('./commands/kiss')
const lick = require('./commands/lick')
const pat = require('./commands/pat')
const pinch = require('./commands/pinch')
const poke = require('./commands/poke')
const sad = require('./commands/sad')
const shy = require('./commands/shy')
const slap = require('./commands/slap')
const smile = require('./commands/smile')
const sorry = require('./commands/sorry')
const stare = require('./commands/stare')
const tickle = require('./commands/tickle')
const wave = require('./commands/wave')
const wink = require('./commands/wink')

const bot = new Telegraf(process.env.BOT_TOKEN)

bot.start((ctx) => ctx.reply(`Добро пожаловать ${ctx.message.from.first_name}!!!\nДля того что бы узнать как использовать команды бота используйте /help`))
bot.help((ctx) => ctx.reply(help.help))
/* все команды взаимодействия */
bot.command('airkiss', (airkiss))
bot.command('bite', (bite))
bot.command('blush', (blush))
bot.command('cry', (cry))
bot.command('cuddle', (cuddle))
bot.command('dance', (dance))
bot.command('drool', (drool))
bot.command('happy', (happy))
bot.command('hit', (hit))
bot.command('hug', (hug))
bot.command('kill', (kill))
bot.command('kiss', (kiss))
bot.command('lick', (lick))
bot.command('pat', (pat))
bot.command('pinch', (pinch))
bot.command('poke', (poke))
bot.command('sad', (sad))
bot.command('shy', (shy))
bot.command('slap', (slap))
bot.command('smile', (smile))
bot.command('sorry', (sorry))
bot.command('stare', (stare))
bot.command('tickle', (tickle))
bot.command('wave', (wave))
bot.command('wink', (wink))


bot.on(() => ctx.reply(`Добро пожаловать ${ctx.message.from.first_name}!!!\nДля того что бы узнать как использовать команды бота используйте /help`))
bot.launch()
// Enable graceful stop
process.once('SIGINT', () => bot.stop('SIGINT'))
process.once('SIGTERM', () => bot.stop('SIGTERM'))


